[BeamformingParams]
qcone_config_id = 1
min_freq = 0.9
max_freq = 1.1
slowness_x_min = -2.1
slowness_x_max = 2.1
slowness_y_min = -2.0
slowness_y_max = 2.0
slowness_step = 0.1
window_length_minimum_periods = 15
window_step_fraction = 0.5
save_average_beamformer_abspower = "True"
save_all_beamformers_abspower = "False"
save_average_beamformer_relpower = "False"
save_all_beamformers_relpower = "False"
extract_peaks_average_beamformer_abspower = "True"
extract_peaks_all_beamformers_abspower = "False"
extract_peaks_average_beamformer_relpower = "False"
extract_peaks_all_beamformers_relpower = "False"
neighborhood_size_xaxis_fraction = 0.1
maxima_threshold = 0.0
best_point_count = 10
beam_portion_threshold = 0.1
semblance_threshold  = -1e9
velocity_threshold = -1e9
prewhiten = "False"
method = "beamforming"
used_component_codes = [ "Z", "E", "N"]
minimum_trace_count = 3